# Generated by Django 5.0.3 on 2024-03-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetLink',
        ),
    ]
