# Generated by Django 5.0.3 on 2024-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0004_delete_resetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
