# Generated by Django 5.0.3 on 2024-04-19 09:49

import volapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0005_posts_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='likes',
            name='emoji',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='reactions',
            field=models.JSONField(default=volapp.models.default_emojis),
        ),
    ]
